### ISSUE TITLE
OOM when run the task

### ISSUE THREAD

**Issue by linbojin** [yaserkl/RLSeq2Seq#10]
Hi, can you help me to solve the following problem:

cmd with tf=1.4.0:
`CUDA_VISIBLE_DEVICES=0 python src/run_summarization.py --mode=train --data_path=data/cnn_dm/finished_files/chunked/train_* --vocab_path=data/cnn_dm/finished_files/vocab --log_root=working_dir/cnn_dm/RLSeq2Seq/ --exp_name=intradecoder-temporalattention-withpretraining --batch_size=32 --max_iter=10 --use_temporal_attention=True --intradecoder=True --rl_training=False`

Error:
`ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [256,50000] and type float
         [[Node: seq2seq/decoder/attention_decoder/output_projection/w/Adagrad/Initializer/Const = Const[_class=["loc:@seq2seq/decoder/attention_decoder/output_projection/w"], dtype=DT_FLOAT, value=Tensor<type: float shape: [256,50000] values: [0.1 0.1 0.1]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]`

**Comment by yaserkl** [comment]
The only solution for OOM (out of memory) is to use a smaller batch size. Depending on your GPU RAM the batch size will defer and some of these models will take a lot of GPU RAMs.

**Comment by linbojin** [comment]
I already set batch_size to 10, but it still didn't work. I think the problem is that the word embedding (256,50000) is too large based on the error info. Can I reduce the vocab size?

**Comment by astorfi** [comment]
@linbojin Please update your fork to make sure your version is up to date. That might be the issue.
Not so sure though. @yaserkl might be able to give you a more accurate answer.

**Comment by linbojin** [comment]
@astorfi Thx, in fact I just downloaded the code and run it yesterday, so it's up-to-date.

**Comment by linbojin** [comment]
@yaserkl  @astorfi  fixed by setting --vocab_size=smaller values. Thx for your codes.
