### ISSUE TITLE
Can the if statement of line 382 of the attention_decoder.py be removed?

### ISSUE THREAD

**Issue by alanlisten** [yaserkl/RLSeq2Seq#19]
Because line 376 already has the following statement:
                if i > 0:
                    tf.get_variable_scope().reuse_variables()

**Comment by yaserkl** [comment]
Please refer to this answer:
https://github.com/yaserkl/RLSeq2Seq/issues/18#issuecomment-429407143

**Comment by yaserkl** [comment]
Yes, that's true. I'll fix it later since it doesn't affect the whole model as it is right now.
