### ISSUE TITLE
Trying to emulate "A Deep Reinforced Model for Abstractive Summarization", trying to find where in code greedy/sampled distribution implemented

### ISSUE THREAD

**Issue by Santosh-Gupta** [yaserkl/RLSeq2Seq#30]
I'm trying to emulate A Deep Reinforced Model for Abstractive Summarization by
Romain Paulus, Caiming Xiong, Richard Socher

And I am trying to verify if everything is implemented correctly.

This image seems to be your map of the architecture described in the model

https://github.com/yaserkl/RLSeq2Seq/blob/master/docs/_img/selfcritic.png

I am guessing that y hat is y hat in the paper, and y hat ^g is equivalent to to y ^s in the paper?

https://snag.gy/suGJTk.jpg

If so, I was wondering where in the repo are these coded, how exactly does the parameters in this section lead to the loss function described in the paper? 

https://github.com/yaserkl/RLSeq2Seq#policy-gradient-w-self-critic-learning-and-temporal-attention-and-intra-decoder-attention

**Comment by yaserkl** [comment]
y^hat is the sampling selection and y^hat^g is the greedy selection. The original paper has a typo in the equation 15. That equation cause a negative loss and we can't minimize it. That's why in our paper we fixed it by swapping the y^hat and y^hat^g.

Regarding the loss, we were never able to get the same results as to what has reported in this paper and the improvement over pointer-generator were very small.

**Comment by Santosh-Gupta** [comment]
Thanks for the insight! 

>Regarding the loss, we were never able to get the same results as to what has reported in this paper and the improvement over pointer-generator were very small.

I think many others were not able to reproduce the results. Many new summarization papers just use regular pointer generator networks for comparison, but they don't use RL. Though I've heard RL is very difficult in general.

Were there any architectures you've tried which resulted in noticeable improvements over pointer-generator networks?

**Comment by Santosh-Gupta** [comment]
> y^hat is the sampling selection and y^hat^g is the greedy selection. The original paper has a typo in the equation 15. That equation cause a negative loss and we can't minimize it. That's why in our paper we fixed it by swapping the y^hat and y^hat^g.
> 
> Regarding the loss, we were never able to get the same results as to what has reported in this paper and the improvement over pointer-generator were very small.

One more question, was the low improvements in Rouge scores, or qualitative analysis of the summaries?
